description: PAWS-PCam-Encoder
name: PAWS::PCam::Encoder_training::Stability_Exp::Resnet18
data:
  worker: 4
labels:
  - resnet18
  - 0.08_split
  - 10_Epochs
  - pcam
  - seed_5
reproducibility:
  experiment_seed: 1643366523 # 1:1643366501 2:1643366507 3:1643366513 4:1643366518 5:1643366523 
hyperparameters:
  copy_data: false
  use_fp16: true
  # Data
  dataset: patchcamelyon
  split_size: 
      type: categorical 
      vals:
      - 0.08
  split_seed: 42
  split_file: false
  multicrop: 6
  label_smoothing: 0.1
  unique_classes_per_rank: false
  data_seed: 152
  # Augmentation Configuration
  # Color
  color_jitter_strength: 0.5
  normalize: true
  # Resize resolutions .... new to configure, standart in code
  std_resize_resolution: 96
  mc_resize_resolution: 48
  # Crop Scaling .... new to configure, standart in code
  crop_scale_min: 0.8
  crop_scale_max: 1.0 
  mc_scale_min: 0.6
  mc_scale_max: 0.9
  # Method
  supervised_views: 2
  unsupervised_batch_size: 64
  supervised_imgs_per_class: 32
  classes_per_batch: 2
  # Encoder Evaluation
  plot_embedding_each: 4094  #262000/64 = 4094 batches per epoch
  # Model
  model_name: 
      type: categorical
      vals:
      - resnet18 #base model
  use_pred_head: false
  output_dim: 128
  pretrained_base_model_path: 'None'
  #'/data/ldap/oliver/determined_checkpoints/paws_histo/simclr_pretrained_models/wide_resnet/checkpoint_9206/state_dict.pth'
  #Fine-tune Model (Prediction Head) .... new to configure, standart in code
  pretrained_paws_model_path: 'None'
  # finetuning 
  number_classes: 2
  # Loss
  me_max: true
  sharpen: 0.25
  temperature: 0.1
  # Optimizer
  weight_decay: 7.191e-4
  start_lr: 0.467
  lr: 1.967
  final_lr: 0.035
  momentum: 0.647
  nesterov: false
  warmup: 4
  # Batch
  global_batch_size: 448
# Single run without hyperparameter tuning
searcher:
  name: single
  metric: t_loss
  smaller_is_better: false
  max_length:
          batches: 40940 # 81880 = 20 Epochs 40940
min_validation_period:
  batches: 4094
checkpoint_storage:
  save_trial_best: 1
  save_trial_latest: 1
  save_experiment_best: 0
resources:
  slots_per_trial: 1
  agent_label: pepper-cluster
  max_slots: 1
max_restarts: 0
# Docker container used
#environment:
#  image:
#    cpu: "deepprojects/determined-pytorch-1.9-tf-2.5-cpu:1.0.0"
#    gpu: "deepprojects/determined-cuda-112-pytorch-1.9-tf-2.5-gpu:1.0.0"
environment:
  image:
    cpu: "deepprojects/determined-pytorch-1.10-cpu:1.1.0"
    gpu: "deepprojects/determined-cuda-113-pytorch-1.10-gpu:1.1.0"
# Bind Avocado into the docker container
bind_mounts:
 - host_path: /data/ldap
   container_path: /data/ldap
   read_only: true
entrypoint: trials:Paws_Encoder