name: SimSiam::Encoder::Hopt::ResNet50::TCGA::50E
description: Check for a good HParams using SimSiam/Triplet with a WideResNet
labels: [sim*, encoder, pcam]
data:
  worker: 4
hyperparameters:
  # -- dataset
  dataset: tcga  
  dataset_val: tcga
  train_augmentation:
    type: categorical
    vals: 
    - medium_stack
    - moco_v2
  val_augmentation: plain
  img_rescale_size: 96
  normalize_data: True
  # -- model
  method: simsiam
  encoder: resnet50
  # wide_resnet28w2
  feature_dim: 2048
  pred_hidden_dim: 512
  # -- optimizer
  momentum:
    type: categorical
    vals:
    - 0.9
    - 0.5
    - 0.1
  lr:
    type: categorical
    vals:
    - 2.0
    - 1.0
    - 0.5
    - 0.1
    - 0.05
  weight_decay: 1e-4
  use_lars: False
  use_scheduler:
    type: categorical
    vals: 
    - False
    - True
  # -- training 
  global_batch_size: 128
  freeze_pred: 999999
  # -- evaluation
  additional_eval: 64900
  plot_specific_iterations: null
  use_knn: True
searcher:
  name: grid
  metric: v_loss
  smaller_is_better: true
  max_length:
     batches: 64900
min_validation_period:
  batches: 1298
checkpoint_storage:
  save_trial_best: 0
  save_trial_latest: 0
  save_experiment_best: 0
resources:
  slots_per_trial: 1
  max_slots: 2
  agent_label: pepper-cluster
max_restarts: 0
environment:
  image:
    cpu: "deepprojects/determined-pytorch-1.11-cpu:1.0.0"
    gpu: "deepprojects/determined-cuda-113-pytorch-1.11-gpu:1.0.0"
bind_mounts:
 - host_path: /data/ldap
   container_path: /data/ldap
   read_only: true
entrypoint: trials:SimSiam