description: PAWS-PCam-Kather-Transfer
name: resnet50::PCam-Kather-Transfer::Stability-Experiment
labels:
  - resnet50
  - finetune
  - pcam-kather-transfer
  - 20_Epochs
  - 0.08_Split
data:
  worker: 4
reproducibility:
  experiment_seed: 1643403513
hyperparameters:
  copy_data: false
  use_fp16: true
  method: paws
  # Data
  dataset: kather_h5_224_norm_split_90_10
  number_classes: 9
  normalize_data: true
  train_augmentation: light_stack
  test_augmentation: plain
  img_rescale_size: 96
  pred_head_structure:
       type: categorical
       vals:
        - one_layer_mlp   
        #- three_layer_mlp
  split_size: 
      type: categorical
      vals:
      - 0.08 # 225 batches = 1 Epoch with batchsize 32 - (90000*0.08)/32 = 225, (90000/256 = 351 Batches per Epoch) -> 7050 Batches
  split_seed: 42
  # Encoder Evaluation
  plot_embedding_each: 225 # 1Epoch # 225 351 
  # Model
  model_name: resnet50 #base model
  dropout_rate: 
      type: categorical
      vals: 
      - 0.0
  use_pred_head: True
  output_dim: 128
  freeze_encoder: 
      type: categorical
      vals:
      - 900 # 2 epochs
      - true # if > max length its never trained
  checkpoint_uuid:
      type: categorical
      vals:
      # pcam encoder
      #- 52e8398c-1741-45e4-8beb-0e426526a2ef #  12091-90899   0.08 Split PCam-Encoder
      #- aacf09b7-8139-4c58-8fa1-e70d89e557a3 #  12078-90507   0.008 Split PCam-Encoder
      #- 17502715-54b4-4e46-b957-0da7bae2a273 #  12080-90509  0.002 Split PCam-Encoder
      #- null 
      # for stability experiments
      - 4f2a51d1-62d6-4419-8918-fed13ec91e7f # Seed 1 12114	91020
      - 1fadbd61-1ed6-4b97-b188-aecd95c19305 # Seed 2 12115	91021
      - db43d340-30a5-4fe0-bd90-f1da9599f899 # Seed 3 12116	91022
      - a0acabe6-d176-4ef0-834a-3df6408a3fd0 # Seed 4 12146	91134
      - 8fd72dd3-8d0c-44d2-8071-e5547b119f99 # Seed 5 12118	91024
  # -- optimizer
  momentum: 0.9
  lr: 
      type: categorical
      vals:
      - 0.005
  weight_decay: 1e-4
  scheduler: true
  use_larc: false
  # -- training 
  global_batch_size: 32 #32 256
# Single run without hyperparameter tuning
searcher:
  name: grid
  metric: v_acc
  smaller_is_better: false
  max_length:
    batches: 4500 # 20 Epochs for 0.08 Split with batch size 32  4500 , 7050 for full set
min_validation_period:
  batches: 225 # 225 351 
checkpoint_storage:
  save_trial_best: 1
  save_trial_latest: 1
  save_experiment_best: 0
resources:
  slots_per_trial: 1
  agent_label: dt-cluster #dt-cluster pepper-cluster
  max_slots: 4
max_restarts: 0
# Docker container used
environment:
  image:
    cpu: "deepprojects/determined-pytorch-1.10-cpu:1.0.0"
    gpu: "deepprojects/determined-cuda-113-pytorch-1.10-gpu:1.0.0"
# Bind Avocado into the docker container
bind_mounts:
 - host_path: "/data/determined/shared_fs/checkpoints"
   container_path: "/checkpoints"
   read_only: true
 - host_path: /data/ldap
   container_path: /data/ldap
   read_only: true
entrypoint: finetune_trial:Finetune