name: SimCLR::WideResnet::Finetune
description: "SplitReduce Transfer Kather-Encoder on Lizard"  # LOOKAT
labels: ["EncoderExperiment 11551"]  # LOOKAT
data:
  worker: 4
hyperparameters:
  method: simclr
  # Data
  dataset: "lizard"  # LOOKAT
  number_classes: SETBYSCRIPT
  normalize_data: true
  train_augmentation: light_stack
  test_augmentation: plain
  img_rescale_size: 96
  keep_enc_fc:
    type: categorical
    vals: [true, false]
  pred_head_features: 128
  pred_head_structure:
    type: categorical
    vals: [one_layer_mlp, three_layer_mlp]
  split_size: SETBYSCRIPT
  split_seed: 42
  # Encoder Evaluation
  plot_embedding_each: SETBYSCRIPT
  # Model
  encoder: wide_resnet28w2
  freeze_encoder: SETBYSCRIPT
  checkpoint_uuid:
    type: categorical
    vals:
      - 887c86b8-7878-496f-b37e-768c26172c18  # LOOKAT
      - null
  # -- optimizer
  momentum: 0.9
  lr: 0.005
  weight_decay: 1e-4
  scheduler: true
  use_larc: false
  # -- training
  global_batch_size: SETBYSCRIPT
# Single run without hyperparameter tuning
searcher:
  name: grid
  metric: v_acc
  smaller_is_better: false
  max_length:
    batches: SETBYSCRIPT
min_validation_period:
  batches: SETBYSCRIPT
checkpoint_storage:
  save_trial_best: 0
  save_trial_latest: 1
  save_experiment_best: 0
resources:
  slots_per_trial: 1
  agent_label: pepper-cluster
  max_slots: 4
max_restarts: 0
# Docker container used
environment:
  image:
    cpu: "deepprojects/determined-pytorch-1.10-cpu:1.0.0"
    gpu: "deepprojects/determined-cuda-113-pytorch-1.10-gpu:1.0.0"
# Bind Avocado into the docker container
bind_mounts:
  - host_path: "/data/determined/shared_fs/checkpoints"
    container_path: "/checkpoints"
    read_only: true
  - host_path: /data/ldap
    container_path: /data/ldap
    read_only: true
entrypoint: finetune_trial:Finetune
reproducibility:
  experiment_seed: SETBYSCRIPT
