name: SimTriplet::FinalEncoder::ResNet18::5
description: This is a nice description, don't you think?
labels: [simtriplet, encoder, kather]
data:
  worker: 4
hyperparameters:
  # -- dataset
  dataset: kather_h5_224_norm  # [Kather, PatchCamelyon, WSSS4LUAD, ICPR, ICPR-BAL, MIDOG]
  dataset_val: kather_h5_224_norm_split_90_10  
  train_augmentation: moco_v2
  val_augmentation: plain
  img_rescale_size: 96
  normalize_data: True
  # -- model
  method: simtriplet
  encoder: resnet18
  feature_dim: 512
  pred_hidden_dim: 128
  # -- optimizer
  lr: 1.0
  momentum: 0.5
  weight_decay: 1e-4
  use_lars: False
  use_scheduler: True
  # -- training 
  global_batch_size: 256
  freeze_pred: 99000 
  # -- evaluation
  plot_specific_iterations: '1'
  additional_eval: 45000
  use_knn: True
reproducibility:
  experiment_seed: 1643366523
  # 1: 1643366501
  # 2: 1643366507
  # 3: 1643366513
  # 4: 1643366518
  # 5: 1643366523
searcher:
  name: grid
  metric: v_loss
  smaller_is_better: true
  max_length:
     batches: 45000
min_validation_period:
  batches: 500
checkpoint_storage:
  save_trial_best: 0
  save_trial_latest: 1
  save_experiment_best: 0
resources:
  slots_per_trial: 1  # Due to the KNN classifier all has to be on one machine
  max_slots: 4
  agent_label: pepper-cluster
max_restarts: 0
environment:
  image:
    cpu: "deepprojects/determined-pytorch-1.10-cpu:1.0.0"
    gpu: "deepprojects/determined-cuda-113-pytorch-1.10-gpu:1.0.0"
bind_mounts:
 - host_path: /data/ldap
   container_path: /data/ldap
   read_only: true
entrypoint: trials:SimSiam