name: SimTrip::SplitExp::ResNet50
description: "Split Reduce Experiment | Encoder: ResNet50-Kather | Downstream: Lizard | Sanity: Check Downstream Setup"
labels: [simtrip, exp_split_reduce, debug]
data:
  worker: 4
hyperparameters:
  # -- dataset
  dataset: lizard  # [kather_h5_224_norm_split_90_10, patchcamelyon, tcga, lizard]
  split_size: 1.0  # Handled by start_split_experiments.py
  normalize_data: true
  train_augmentation: light_stack
  test_augmentation: plain
  img_rescale_size: 96
  # -- model
  method: simtriplet
  encoder: resnet50  # resnet18, resnet50, wide_resnet28w2
  pred_head_structure:
    type: categorical
    vals:  # [three_layer_mlp, two_layer_mlp, one_layer_mlp, simsiam=default]
    - one_layer_mlp  
    - three_layer_mlp
  pred_head_features: 512 # only relevant fot two_layer_mlp and three_layer_mlp
  number_classes: 9  # Handled by start_split_experiments.py
  keep_enc_fc: 
    type: categorical
    vals:
    - true
    - false
  freeze_encoder:  # Freeze for 4 Epochs -- [true, false, or int for warm_up]
    type: categorical
    vals:
    - 900  # Handled by start_split_experiments.py
    - true
  checkpoint_uuid: 
    type: categorical
    vals:
    - null
    # SimTrip
    # - 4c30359c-2a4e-44e5-a581-4bdbc3aaf247 # ResNet18
    - 4affbe7c-f678-454a-b3c0-baa279781f73  # ResNet50
    # - 02f7c373-2ada-4e98-977e-a522f9eca676  # Wide_ResNet
    # SimSiam
    # - f3967262-7c4f-43e2-bab9-02dbd7892864  # ResNet18
    # - 26249c94-9316-4f6d-8061-04a48c67655a  # ResNet50
    # - e74c1b83-dd08-4413-8bd2-75554e553006  # Wide_ResNet 
  # -- optimizer  
  lr: 
    type: categorical
    vals:
    - 0.005
    - 0.05
  momentum: 0.9
  weight_decay: 1e-4
  use_larc: false
  scheduler: True
  # -- training 
  global_batch_size: 256  # Handled by start_split_experiments.py
  # -- evaluation
  plot_embedding_each: 7020  # Handled by start_split_experiments.py
reproducibility:
  experiment_seed: 1643118217
searcher:
  name: grid
  metric: v_loss
  smaller_is_better: true
  max_length:
    batches: 7020  # Handled by start_split_experiments.py
min_validation_period:
  batches: 351  # Handled by start_split_experiments.py
checkpoint_storage:
  save_trial_best: 0
  save_trial_latest: 1
  save_experiment_best: 0
resources:
  slots_per_trial: 1
  max_slots: 4
  agent_label: pepper-cluster
max_restarts: 0
environment:
  image:
    cpu: "deepprojects/determined-pytorch-1.11-cpu:1.0.0"
    gpu: "deepprojects/determined-cuda-113-pytorch-1.11-gpu:1.0.0"
bind_mounts:
 - host_path: "/data/determined/shared_fs/checkpoints"
   container_path: "/checkpoints"
   read_only: true
 - host_path: /data/ldap
   container_path: /data/ldap
   read_only: true
entrypoint: finetune_trial:Finetune