name: SimTrip::PCam::Encoder::Wide_ResNet28::S5
description: final PCam encoder
labels: [simtriplet, encoder, pcam, final]
data:
  worker: 4
hyperparameters:
  # -- dataset
  dataset: patchcamelyon  # [Kather, PatchCamelyon, WSSS4LUAD, ICPR, ICPR-BAL, MIDOG]
  dataset_val: patchcamelyon  
  train_augmentation: moco_v2
  val_augmentation: plain
  img_rescale_size: 96
  normalize_data: True
  # -- model
  method: simtriplet
  encoder: wide_resnet28w2
  feature_dim: 512
  pred_hidden_dim: 128
  # -- optimizer
  lr: 0.5
  momentum: 0.5
  weight_decay: 1e-4
  use_lars: False
  use_scheduler: True
  # -- training 
  global_batch_size: 64
  freeze_pred: 204800 
  # -- evaluation
  additional_eval: 204800
  plot_specific_iterations: '1'
  use_knn: True
reproducibility:
  experiment_seed: 1643404524
  # 1: 1643404500
  # 2: 1643404508
  # 3: 1643404513
  # 4: 1643404518
  # 5: 1643404524
searcher:
  name: grid
  metric: v_loss
  smaller_is_better: true
  max_length:
     batches: 204800
min_validation_period:
  batches: 2048
checkpoint_storage:
  save_trial_best: 0
  save_trial_latest: 1
  save_experiment_best: 0
resources:
  slots_per_trial: 1  # Due to the KNN classifier all has to be on one machine
  max_slots: 2
  agent_label: pepper-cluster
max_restarts: 0
environment:
  image:
    cpu: "deepprojects/determined-pytorch-1.11-cpu:1.0.0"
    gpu: "deepprojects/determined-cuda-113-pytorch-1.11-gpu:1.0.0"
bind_mounts:
 - host_path: /data/ldap
   container_path: /data/ldap
   read_only: true
entrypoint: trials:SimSiam